version: '3.8'

services:
    syaaraat:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: syaaraat
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
        ports:
            - "8032:80"
        depends_on:
            - mysql-db

    mysql-db:
        image: mysql:8.0
        container_name: syaaraat-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: syaaraat
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3332:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: syaaraat-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql-db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8033:80"
        depends_on:
            - mysql-db

volumes:
    mysql_data:
        driver: local
